### ISSUE TITLE
Support other CRS than 4326 (or allow to relax range validation rule)

### ISSUE THREAD

**Issue by autra** [gb-libs/pydantic-geojson#15]
While the geojson spec explicitly says GeoJSON should be in 4326, it does not completely closes alternatives:

> However, where all involved parties have a prior arrangement, alternative coordinatereference systems can be used without risk of data being misinterpreted.

It's actually my case, where the backend and the frontend agrees on some reference system in some case.

For this use case, it'd be nice to either be able to use another CRS, or simply have an option not to validate coordinates range.

Thanks.

**Comment by folt** [comment]
Hi @autra. Having studied the standard, I noticed that in GeoJSON the `"coordinates"` field can indeed be in different CRS.

It is possible to get the expected behavior yourself by overriding the `LonField` and `LatField` fields in the `Coordinates` class.

It could look something like this:

```
MyLonField = Annotated[
    Union[float, int],
    Field(
        title='Coordinate longitude',
        gt=-1,
        lt=1,
    ),
]

MyLatField = Annotated[
    Union[float, int],
    Field(
        title='Coordinate latitude',
        gt=-1,
        lt=1,
    ),
]

class MyCoordinates(NamedTuple):
    lon: MyLonField
    lat: MyLatField

class MyPointModel(PointModel):
    coordinates: MyCoordinates
```

Where the restriction for validation can be specified independently. It is worth noting that different standards have different validation rules.
Feel free to contribute with the implementation of coordinate fields for different CRS.
